# -*- coding: utf-8 -*-
"""pan_banking_insights_estrategicos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iRJPn6uH4-E2uSO59-AdlKay1p-UtZ1z

# Case - Análise de Dados - Clientes Banking Banco PAN

### Análise de Dados – Clientes Banking Banco PAN

#📊 Objetivo Geral:
Realizar o tratamento, padronização e preparação das três bases fornecidas
(Base Nome, Base UF e Base Geral) para posterior análise exploratória,
modelagem relacional e geração de insights de negócio em ambiente SQL Server
e ferramenta de visualização.

###📌 **Observação:**
Os arquivos carregados no Google Colab possuem armazenamento temporário.
Sempre que necessário, o upload deve ser realizado novamente.

# 1. Instalação e Importação das bibliotecas necessárias
"""

# Commented out IPython magic to ensure Python compatibility.
#Instalando o Pandas
# %pip install pandas

#Importando as bibliotecas para tratamento das bases

import pandas as pd # Pandas: usado para manipulação e análise de dados (tabelas, CSV, Excel).
import re # Regex (Regular Expressions): usado para buscar, filtrar e manipular textos por padrões.

"""# 2. Upload do arquivo XLS contendo as três bases"""

# Carregar base para o ambiente do Colab
from google.colab import files
uploaded = files.upload()

# # Carrega somente a primeira aba (onde as três bases foram consolidadas lado a lado)
raw = pd.read_excel('Bases_dados.xlsx', sheet_name=0)

"""# 3. Visualização inicial dos dados (estrutura bruta)"""

# Validação da estrutura inicial e leitura da primeira linha
df = pd.read_excel("Bases_dados.xlsx")
print(df.head())

"""#4. Identificação e separação das três bases posicionadas lado a lado na planilha"""

# A planilha foi construída agrupando tabelas por blocos de colunas.
raw.head(20) # Visualização estendida para entender a disposição das bases

"""#4.1 Separação das bases"""

#A planilha foi construída agrupando tabelas por blocos de colunas.
raw = pd.read_excel("Bases_dados.xlsx", sheet_name=0) # Visualização estendida para entender a disposição das bases

# Seleção dos blocos de colunas correspondentes às três bases
base_nome  = raw.iloc[:, 0:3]       # colunas 0,1,2
base_uf    = raw.iloc[:, 5:9]       # colunas 5,6,7,8
base_geral = raw.iloc[:, 11:16]     # colunas 11,12,13,14,15

"""# 4.2. Validação das bases separadas
- Alternar o nome da base para validação de cada uma - Valores (base_nome, base_uf ou base_geral)
"""

# Validdação das primeiras linhas
print("===== BASES SEPARADAS: VALIDAÇÃO =====")

print("\n1. Primeiras linhas (head):")
print(base_nome.head())

print("\n2. Formato (linhas, colunas):")
print(base_nome.shape)

print("\n3. Nome das colunas:")
for col in base_nome.columns:
    print(col)

print("\n4. Tipos das colunas (dtypes):")
print(base_nome.dtypes)

"""#4.3 - Leitura dos Arquivos"""

#print(df.columns) #A função columns nos retorna o nome das colunas do data set

for col in df.columns: #Retornando as colunas com nome "Unnamed"
  print(col)

"""# 5. Tratamento das bases: limpeza de linhas e reconstrução de cabeçalhos"""

# Remoção de linhas totalmente vazias
base_nome = base_nome.dropna(how="all").reset_index(drop=True)
base_uf = base_uf.dropna(how="all").reset_index(drop=True)
base_geral = base_geral.dropna(how="all").reset_index(drop=True)

# A primeira linha contém os nomes das colunas de cada base
base_nome.columns = base_nome.iloc[0]
base_uf.columns = base_uf.iloc[0]
base_geral.columns = base_geral.iloc[0]

# Remoção da linha do cabeçalho incorporado
base_nome = base_nome.iloc[1:].reset_index(drop=True)
base_uf = base_uf.iloc[1:].reset_index(drop=True)
base_geral = base_geral.iloc[1:].reset_index(drop=True)

"""# 5.1 Revalidação da estrutura após limpeza
- Para as demais bases - alterar o nome da base: Valores = base_nome, base_uf ou base_geral)
"""

print("===== VALIDAÇÃO DADOS DAS BASES =====")

print("\n1. Primeiras linhas (head):")
print(base_geral.head())

print("\n2. Formato (linhas, colunas):")
print(base_geral.shape)

print("\n3. Nome das colunas:")
for col in base_geral.columns:
    print(col)

print("\n4. Tipos das colunas (dtypes):")
print(base_geral.dtypes)

"""# 5.2 Tratamento da coluna 'renda' (Base Nome)
- Conversão segura de ddo tipo "object" → "float64"
"""

base_nome['renda'].unique()[:20]

def limpa_numero(valor):
    if pd.isna(valor):
        return None
    valor = str(valor)

#Remove caracteres não numéricos e converte para inteiro.
#Retorna None para valores inválidos ou vazios.

    valor = re.sub(r'\D', '', valor)
    if valor == "":
        return None
    return int(valor)

# Aplica a função de limpeza e converte a coluna 'renda' para inteiro
base_nome['renda'] = base_nome['renda'].apply(limpa_numero)

# Verifica o tipo de dado após o tratamento
base_nome['renda'].dtype

"""# 5.3 Tratamento de acentuação (Base UF)"""

# Correção de caracteres corrompidos por encoding -  "orgsup_lotacao_instituidor_pensao"
base_uf['orgsup_lotacao_instituidor_pensao'] = (
    base_uf['orgsup_lotacao_instituidor_pensao']
        .astype(str)
        .str.encode('latin1', errors='ignore')
        .str.decode('utf-8', errors='ignore')
)

"""#5.4 Tratamento da coluna de data (Base Geral)"""

# Conversão "dt_nascimento" para o padrão YYYY-MM-DD aceito pelo SQL Server
base_geral['dt_nascimento'] = pd.to_datetime(
    base_geral['dt_nascimento'],
    errors='coerce',
    format='%Y-%m-%d %H:%M:%S'
)

# Converte a data para o formato 'YYYY-MM-DD' deixando como tipo "objecto" facilitando a exportação e qualidade dos dados em .csv
base_geral['dt_nascimento'] = base_geral['dt_nascimento'].dt.strftime('%Y-%m-%d')

"""# 5.5 Validação final das três bases após tratamento
- Para as demais bases - alterar o nome da base: Valores = base_nome, base_uf ou base_geral)
"""

print("===== VALIDAÇÃO FINAL =====")

print("\n1. Primeiras linhas (head):")
print(base_geral.head())

print("\n2. Formato (linhas, colunas):")
print(base_geral.shape)

print("\n3. Nome das colunas:")
for col in base_geral.columns:
    print(col)

print("\n4. Tipos das colunas (dtypes):")
print(base_geral.dtypes)

print(base_nome.shape) # Exibe a quantidade de linhas e colunas do DataFrame base_nome
print(base_uf.shape) # Exibe a quantidade de linhas e colunas do DataFrame base_uf
print(base_geral.shape) # Exibe a quantidade de linhas e colunas do DataFrame base_geral

#base_nome.head()
#base_uf.head()
#base_geral.head()

"""#6. Salvando as três bases tratadas para .csv"""

base_nome.to_csv("base_nome.csv", index=False)
base_uf.to_csv("base_uf.csv", index=False)
base_geral.to_csv("base_geral.csv", index=False)

"""# 7. Download dos arquivos .csv processados"""

from google.colab import files

files.download('base_nome.csv')
files.download('base_uf.csv')
files.download('base_geral.csv')